name = "retail-buddy"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-11-18"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "retailbuddy"
database_id = "7284c20c-bf21-40ee-9838-cf826a945b57"
