name = "retail-buddy"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "retailbuddy"
database_id = "648e9e90-5b2f-48e1-a6e9-59b9da996262"
 # User will need to update this
