name = "retail-buddy"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "retailbuddy"
database_id = "7284c20c-bf21-40ee-9838-cf826a945b57"
 # User will need to update this
